### ISSUE TITLE
valid range for longitudes

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/cordex-cmip6-cmor-tables#22]
At the moment, valid ranges are for longitudes are (-180.0, 180.0) degress: https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables/commit/13457ead22c4bdf131aa00c77d0a2fbaf393ae34

CMIP6 models have longitudes from 0-360.0

**Comment by gnikulin** [comment]
In CORDEX there are both cases (-180.0 to 180.0 and 0 to 360) depending on the CORDEX domains, perhaps the valid ranges can be -180.0 to 360 ?

**Comment by gnikulin** [comment]
Yes, in CORDEX the valid range should be -180.0 to 360.
