### ISSUE TITLE
`out_name` of longitude / latitude variables

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/cordex-cmip6-cmor-tables#69]
I think in CMIP6, the names of longitude and latitude coordinates is `longitude` and `latitude` if they are so-called *auxiliary coordinate variable* (e.g., 2D projected coordinates with a grid mapping) but they are called `lon` / `lat` if they are normal coordinate variables (e.g., the native coordinates of the grid). Should we also use `longitude` / `latitude` (if a grid_mapping is present and those are 2D coordinates) or go back to the CMIP5 standard where CORDEX uses `lon` / `lat` for the 2D auxiliary coordinates?

https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables/blob/80f7f510266884d372d68de6f4d63ffd68255f18/Tables/CORDEX-CMIP6_grids.json#L117-L136

I don't have a preference, right now we use it like in the original `CMIP6_grids` table. 

@gnikulin @sol1105  do you have a preference?

**Comment by larsbuntemeyer** [comment]
I renamed now to `lon` /`lat` to be consistent with the current [archive specs draft](https://cordex.org/wp-content/uploads/2023/11/CORDEX-CMIP6_archive_specs_SOD_landscape.pdf) (section 6). Keep the issue open for now...

**Comment by larsbuntemeyer** [comment]
See also https://github.com/PCMDI/cmor/issues/470#issuecomment-482143890

**Comment by gnikulin** [comment]
In CORDEX-CMIP5 we always used `lon` / `lat` even for the regular grids. As already mentioned in https://github.com/PCMDI/cmor/issues/470 the CF conventions uses lat and lon throughout its examples, but doesn't define these variable names as a requirement for data with two dimensional coordinates. CMIP6 also doesn't define `longitude` / `latitude` as a requirement, it's up to the data provider, although CMOR uses "latitude" and "longitude" for auxiliary coordinates (not "lat" and "lon"). 

I completely agree to use only `lon` / `lat` in CORDEX-CMIP6 for all cases.

**Comment by larsbuntemeyer** [comment]
Ok, agreed.
